- hosts: general webservers dbservers mailservers gameservers
  user: root

  vars_files:
    - base-config.yaml.vars

  tasks:
    - name: Update apt cache
      apt: update_cache=yes cache_valid_time=86400

    - name: Install required programs
      apt: name={{ item }} state=latest
      with_items:
        - ufw
        - rsync
        - fail2ban
        - monit

    - name: Enable firewall
      ufw:
        state: enabled

    - name: Allow SSH on port 22/tcp
      ufw:
          rule: allow
          port: 22
          proto: tcp

    - name: Install /etc/ssh/sshd_config
      template: src=configs/etc/ssh/sshd_config.j2
        dest=/etc/ssh/sshd_config
        backup=yes
        owner=0 group=0 mode=0644
        validate='/usr/sbin/sshd -T -f %s'
      notify:
        - restart sshd

    - name: Create /root/.ssh
      action: file path=/root/.ssh state=directory
        owner=0 group=0 mode=0755

    - name: Upload /root/.ssh/authorized_keys
      action: copy src=configs/root/.ssh/authorized_keys
        dest=/root/.ssh/authorized_keys
        owner=0 group=0 mode=644

    - name: Upload /root/.bashrc
      template: src=configs/root/.bashrc.j2
        dest=/root/.bashrc
        backup=yes
        owner=0 group=0 mode=0644

    - name: Upload /etc/monit/conf.d/alert-preferences.conf
      action: copy src=configs/etc/monit/conf.d/alert-preferences.conf
        dest=/etc/monit/conf.d/alert-preferences.conf
        owner=0 group=0 mode=644
      notify:
        - restart monit

    - name: Upload /etc/monit/conf.d/host-watch.conf
      action: copy src=configs/etc/monit/conf.d/host-watch.conf
        dest=/etc/monit/conf.d/host-watch.conf
        owner=0 group=0 mode=644
      notify:
        - restart monit

    - name: Upload /etc/monit/conf.d/sshd.conf
      action: copy src=configs/etc/monit/conf.d/sshd.conf
        dest=/etc/monit/conf.d/sshd.conf
        owner=0 group=0 mode=644
      notify:
        - restart monit

    - name: Upload /etc/monit/conf.d/postfix.conf
      action: copy src=configs/etc/monit/conf.d/postfix.conf
        dest=/etc/monit/conf.d/postfix.conf
        owner=0 group=0 mode=644
      notify:
        - restart monit

  handlers:
    - name: restart sshd
      service: name=sshd state=restarted
    - name: restart monit
      service: name=monit state=restarted