# Provides a solid base configuration for Debian servers
# 
# Author: Chuck Findlay <chuck@findlayis.me>
# License: LGPL v3.0
- hosts: all
  user: root

  vars_files:
    - base-config.yaml.vars

  tasks:
    - name: Update apt cache
      apt: update_cache=yes cache_valid_time=86400

    - name: Install required programs
      apt: name={{ item }} state=latest
      with_items:
        - ufw
        - rsync
        - fail2ban
        - monit
        - unattended-upgrades

    - name: Copy /etc/apt/listchanges.conf
      template: src=configs/etc/apt/listchanges.conf.j2
        dest=/etc/apt/listchanges.conf
        backup=no
        owner=0 group=0 mode=0644

    - name: Enable firewall
      ufw:
        state: enabled
      when: no_ufw_hosts not in inventory_hostname

    - name: Allow SSH on port 22/tcp
      ufw:
          rule: allow
          port: 22
          proto: tcp
      when: no_ufw_hosts not in inventory_hostname

    - name: Install /etc/ssh/sshd_config
      template: src=configs/etc/ssh/sshd_config.j2
        dest=/etc/ssh/sshd_config
        backup=no
        owner=0 group=0 mode=0644
        validate='/usr/sbin/sshd -T -f %s'
      notify:
        - restart sshd

    - name: Create /root/.ssh
      action: file path=/root/.ssh state=directory
        owner=0 group=0 mode=0755

    - name: Upload /root/.ssh/authorized_keys
      action: copy src=configs/root/.ssh/authorized_keys
        dest=/root/.ssh/authorized_keys
        owner=0 group=0 mode=644

    - name: Upload /root/.bashrc
      template: src=configs/root/.bashrc.j2
        dest=/root/.bashrc
        backup=no
        owner=0 group=0 mode=0644

    - name: Upload /etc/monit/conf.d/alert-preferences.conf
      template: src=configs/etc/monit/conf.d/alert-preferences.conf.j2
        dest=/etc/monit/conf.d/alert-preferences.conf
        backup=no
        owner=0 group=0 mode=0644
      notify:
        - restart monit

    - name: Upload /etc/monit/conf.d/host-watch.conf
      action: copy src=configs/etc/monit/conf.d/host-watch.conf
        dest=/etc/monit/conf.d/host-watch.conf
        owner=0 group=0 mode=644
      notify:
        - restart monit

    - name: Upload /etc/monit/conf.d/sshd.conf
      action: copy src=configs/etc/monit/conf.d/sshd.conf
        dest=/etc/monit/conf.d/sshd.conf
        owner=0 group=0 mode=644
      notify:
        - restart monit

    - name: Upload /etc/monit/conf.d/postfix.conf
      action: copy src=configs/etc/monit/conf.d/postfix.conf
        dest=/etc/monit/conf.d/postfix.conf
        owner=0 group=0 mode=644
      notify:
        - restart monit

  handlers:
    - name: restart sshd
      service: name=sshd state=restarted
    - name: restart monit
      service: name=monit state=restarted