- hosts: general webservers dbservers mailservers gameservers
  user: root

  vars_files:
    - ~/playbooks/baseconfigs.yaml.vars

  tasks:
    - name: Update apt cache
      apt: update_cache=yes cache_valid_time=86400

    - name: Install required programs
      apt: name={{ item }} state=latest
      with_items:
        - ufw
        - rsync

    - name: Enable firewall
      ufw:
        state: enabled

    - name: Allow SSH on port 22/tcp
      ufw:
          rule: allow
          port: 22
          proto: tcp

    - name: Install /etc/ssh/sshd_config
      template: src=~/configs/ssh/sshd_config.j2
        dest=/etc/ssh/sshd_config
        backup=yes
        owner=0 group=0 mode=0644
        validate='/usr/sbin/sshd -T -f %s'
      notify:
        - restart sshd

    - name: Create /root/.ssh
      action: file path=/root/.ssh state=directory
        owner=0 group=0 mode=0755

    - name: Upload /root/.ssh/authorized_keys
      action: copy src=~/configs/ssh/authorized_keys
        dest=/root/.ssh/authorized_keys
        owner=0 group=0 mode=644

    - name: Upload /root/.bashrc
      template: src=~/configs/bash/rootbashrc.j2
        dest=/root/.bashrc
        backup=yes
        owner=0 group=0 mode=0644

  handlers:
    - name: restart sshd
      service: name=sshd state=restarted
