# Provides a solid base configuration for Debian servers
# 
# Author: Chuck Findlay <chuck@findlayis.me>
# License: LGPL v3.0
- hosts: all
  user: root

  vars_files:
    - base-config.yaml.vars

  tasks:
    - name: Update apt cache
      apt: update_cache=yes cache_valid_time=86400

    - name: Install required programs
      apt:
        name:
          - rsync
          - fail2ban
          - unattended-upgrades
          - aptitude
        state: present
        autoclean: yes

    - name: Copy /etc/apt/listchanges.conf
      template: src=configs/etc/apt/listchanges.conf.j2
        dest=/etc/apt/listchanges.conf
        backup=no
        owner=0 group=0 mode=0644

    - name: Install /etc/ssh/sshd_config
      template: src=configs/etc/ssh/sshd_config.j2
        dest=/etc/ssh/sshd_config
        backup=no
        owner=0 group=0 mode=0644
        validate='/usr/sbin/sshd -T -f %s'
      notify:
        - restart sshd

    - name: Create /root/.ssh
      action: file path=/root/.ssh state=directory
        owner=0 group=0 mode=0755

    - name: Upload /root/.ssh/authorized_keys
      action: copy src=configs/root/.ssh/authorized_keys
        dest=/root/.ssh/authorized_keys
        owner=0 group=0 mode=644

    - name: Upload /root/.bashrc
      template: src=configs/root/.bashrc.j2
        dest=/root/.bashrc
        backup=no
        owner=0 group=0 mode=0644

    - name: Upload /root/.forward
      template: src=configs/root/.forward.j2
        dest=/root/.forward
        backup=no
        owner=0 group=0 mode=0644

  handlers:
    - name: restart sshd
      service: name=sshd state=restarted