# Sets up a solid postfix/dovecot/spamassassin/clamav configuration backed by MySQL
# Designed for one server. Relays should be configured seperately.
# 
# Not yet usable
# Author: Chuck Findlay <chuck@findlayis.me>
# License: LGPL v3.0
- hosts: mailservers
  user: root

  vars_files:
    - ~/playbooks/mail-primaries.yaml.vars

  tasks:
    - name: Update apt cache
      apt: update_cache=yes cache_valid_time=86400

    - name: Install depends
      apt: name={{ item }} state=latest
      with_items:
        - postfix
        - postfix-policyd-spf-perl
        - opendkim
        - dovecot

    - name: Copy /etc/mailname
      action: copy src=~/configs/postfix/mailname.j2
        dest=/etc/postfix/conf.d/mailname.j2
        owner=0 group=0 mode=644

    - name: Copy /etc/postfix/main.cf
      template: src=~/configs/postfix/main.cf.j2
        dest=/etc/postfix/main.cf
        backup=yes
        owner=0 group=0 mode=0644

    - name: Copy /etc/postfix/master.cf
      template: src=~/configs/postfix/master.cf.j2
        dest=/etc/postfix/master.cf
        backup=yes
        owner=0 group=0 mode=0644

    - name: Create /etc/postfix/conf.d directory
      action: file path=/etc/postfix/conf.d state=directory
        owner=0 group=0 mode=0755

    - name: Copy /etc/postfix/conf.d/helo_access
      action: copy src=~/configs/postfix/conf.d/helo_access
        dest=/etc/postfix/conf.d/helo_access
        owner=0 group=0 mode=644

    - name: Copy /etc/postfix/conf.d/sender_access
      action: copy src=~/configs/postfix/conf.d/sender_access
        dest=/etc/postfix/conf.d/sender_access
        owner=0 group=0 mode=644

    - name: Copy /etc/postfix/conf.d/tls_policy
      action: copy src=~/configs/postfix/conf.d/tls_policy
        dest=/etc/postfix/conf.d/tls_policy
        owner=0 group=0 mode=644

  handlers:
    - name: restart postfix
      service: name=postfix state=restarted
