# Sets up a solid postfix/dovecot/spamassassin/clamav configuration backed by MySQL
# Designed for one server. Relays should be configured seperately.
# 
# Not yet usable
# Author: Chuck Findlay <chuck@findlayis.me>
# License: LGPL v3.0
- hosts: mailservers
  user: root

  vars_files:
    - mail-primaries.yaml.vars

  tasks:
    - name: Update apt cache
      apt: update_cache=yes cache_valid_time=86400

    - name: Install depends
      apt: name={{ item }} state=latest
      with_items:
        - postfix
        - postfix-mysql
        - postfix-policyd-spf-perl
        - opendkim
        - dovecot-mysql
        - dovecot-sieve
        - dovecot-lmtpd
        - dovecot-imapd
        - dovecot-pop3d
        - dovecot-sieve

    - name: Allow SMTP on port 25/tcp
      ufw:
          rule: allow
          port: 25
          proto: tcp

    - name: Allow SMTP Submision on port 587/tcp
      ufw:
          rule: allow
          port: 587
          proto: tcp

    - name: Copy /etc/mailname
      template: src=configs/etc/mailname.j2
        dest=/etc/mailname
        backup=no
        owner=0 group=0 mode=0644
      notify:
        - restart postfix

    - name: Copy /etc/postfix/main.cf
      template: src=configs/etc/postfix/main.cf.j2
        dest=/etc/postfix/main.cf
        backup=no
        owner=0 group=0 mode=0644
      notify:
        - restart postfix

    - name: Copy /etc/postfix/master.cf
      template: src=configs/etc/postfix/master.cf.j2
        dest=/etc/postfix/master.cf
        backup=no
        owner=0 group=0 mode=0644
      notify:
        - restart postfix

    - name: Create /etc/postfix/conf.d directory
      action: file path=/etc/postfix/conf.d state=directory
        owner=0 group=0 mode=0755

    - name: Copy /etc/postfix/conf.d/helo_access
      action: copy src=configs/etc/postfix/conf.d/helo_access
        dest=/etc/postfix/conf.d/helo_access
        owner=0 group=0 mode=644
      notify:
        - postmap helo_access

    - name: Copy /etc/postfix/conf.d/sender_access
      action: copy src=configs/etc/postfix/conf.d/sender_access
        dest=/etc/postfix/conf.d/sender_access
        owner=0 group=0 mode=644
      notify:
        - postmap sender_access

    - name: Copy /etc/postfix/conf.d/tls_policy
      action: copy src=configs/etc/postfix/conf.d/tls_policy
        dest=/etc/postfix/conf.d/tls_policy
        owner=0 group=0 mode=644
      notify:
        - postmap tls_policy

    - name: Copy /etc/postfix/conf.d/mysql-virtual-alias-maps.cf
      template: src=configs/etc/postfix/conf.d/mysql-virtual-alias-maps.cf.j2
        dest=/etc/postfix/conf.d/mysql-virtual-alias-maps.cf
        backup=no
        owner=0 group=0 mode=0644
      notify:
        - restart postfix

    - name: Copy /etc/postfix/conf.d/mysql-virtual-mailbox-domains.cf
      template: src=configs/etc/postfix/conf.d/mysql-virtual-mailbox-domains.cf.j2
        dest=/etc/postfix/conf.d/mysql-virtual-mailbox-domains.cf
        backup=no
        owner=0 group=0 mode=0644
      notify:
        - restart postfix

    - name: Copy /etc/postfix/conf.d/mysql-virtual-mailbox-maps.cf
      template: src=configs/etc/postfix/conf.d/mysql-virtual-mailbox-maps.cf.j2
        dest=/etc/postfix/conf.d/mysql-virtual-mailbox-maps.cf
        backup=no
        owner=0 group=0 mode=0644
      notify:
        - restart postfix

    - name: Copy /etc/postfix/conf.d/mysql-virtual-relay-domains.cf
      template: src=configs/etc/postfix/conf.d/mysql-virtual-relay-domains.cf.j2
        dest=/etc/postfix/conf.d/mysql-virtual-relay-domains.cf
        backup=no
        owner=0 group=0 mode=0644
      notify:
        - restart postfix

  handlers:
    - name: restart postfix
      service: name=postfix state=restarted

    - name: postmap helo_access
      command: /usr/sbin/postmap /etc/postfix/conf.d/helo_access

    - name: postmap sender_access
      command: /usr/sbin/postmap /etc/postfix/conf.d/sender_access

    - name: postmap tls_policy
      command: /usr/sbin/postmap /etc/postfix/conf.d/tls_policy
