# Sets up a solid postfix/dovecot configuration backed by MySQL
# Designed for one server. Relays should be configured seperately.
#
# Things that need to be changed to use:
# - Edit mail-primaries.yaml.vars
# - Add dkim keys to configs/etc/dkimkeys
# - Create SigningTable, KeyTable, and TrustedHosts in configs/etc/opendkim and populate properly, pointing to /etc/dkimkeys/?.key for each key
# - Mount a storage for the mail as /var/mail
# - Set hostname of server to FQDN you need it to be, and adjust DNS records accordingly
# 
# Work in progress.
# Author: Chuck Findlay <chuck@findlayis.me>
# License: LGPL v3.0
- hosts: mailservers
  user: root

  vars_files:
    - mail-primaries.yaml.vars

  tasks:
    - name: Update apt cache
      apt: update_cache=yes cache_valid_time=86400

    - name: Install depends
      apt: name={{ item }} state=latest
      with_items:
        - postfix
        - postfix-mysql
        - postfix-policyd-spf-perl
        - libsasl2-modules
        - opendkim
        - dovecot-mysql
        - dovecot-sieve
        - dovecot-lmtpd
        - dovecot-imapd
        - dovecot-pop3d
        - dovecot-sieve
        - dovecot-managesieved
        - certbot


    - name: Copy /etc/mailname
      template: src=configs/etc/mailname.j2
        dest=/etc/mailname
        backup=no
        owner=0 group=0 mode=0644
      notify:
        - restart postfix

    #                #
    # ufw (firewall) #
    #                #

    - name: Allow SMTP on port 25/tcp
      ufw:
          rule: allow
          port: 25
          proto: tcp

    - name: Allow SMTP Submision on port 587/tcp
      ufw:
          rule: allow
          port: 587
          proto: tcp

    - name: Allow IMAPS on port 993/tcp
      ufw:
          rule: allow
          port: 993
          proto: tcp

    - name: Allow managesieve on port 4190/tcp
      ufw:
          rule: allow
          port: 4190
          proto: tcp

    - name: Allow HTTP port 80 for ACME challenge for certbot
      ufw:
          rule: allow
          port: 80
          proto: tcp

    #                         #
    # Letsencrypt certificate #
    #                         #

    - name: Check if letsencrypt certificate exists
      stat:
        path: /etc/letsencrypt/live/{{ ansible_fqdn }}/fullchain.pem
      register: cert_result

    - name: Run certbot
      command: /usr/bin/certbot certonly --standalone -d {{ ansible_fqdn }}
      when: cert_result.stat.exists == False 

    #          #
    # Opendkim #
    #          #

    - name: Copy /etc/opendkim.conf
      template: src=configs/etc/opendkim.conf.j2
        dest=/etc/opendkim.conf
        backup=no
        owner=0 group=0 mode=0644
      notify:
        - restart opendkim

    - name: Copy dkim keys to /etc/dkimkeys/
      action: copy src=configs/etc/dkimkeys/
        dest=/etc/dkimkeys/
        owner=opendkim group=opendkim mode=0600
      notify:
        - restart opendkim

    - name: Copy /etc/opendkim/
      action: copy src=configs/etc/opendkim/
        dest=/etc/opendkim/
        owner=0 group=0 mode=0644
      notify:
        - restart opendkim

    #         #
    # Dovecot #
    #         #

    - name: Copy /etc/dovecot/dovecot.conf
      template: src=configs/etc/dovecot/dovecot.conf.j2
        dest=/etc/dovecot/dovecot.conf
        backup=no
        owner=0 group=0 mode=0644
      notify:
        - restart dovecot

    - name: Copy /etc/dovecot/dovecot-sql.conf.ext
      template: src=configs/etc/dovecot/dovecot-sql.conf.ext.j2
        dest=/etc/dovecot/dovecot-sql.conf.ext
        backup=no
        owner=0 group=dovecot mode=0640
      notify:
        - restart dovecot

    - name: Copy /etc/dovecot/conf.d/10-auth.conf
      template: src=configs/etc/dovecot/conf.d/10-auth.conf.j2
        dest=/etc/dovecot/conf.d/10-auth.conf
        backup=no
        owner=0 group=0 mode=0644
      notify:
        - restart dovecot

    - name: Copy /etc/dovecot/conf.d/10-director.conf
      template: src=configs/etc/dovecot/conf.d/10-director.conf.j2
        dest=/etc/dovecot/conf.d/10-director.conf
        backup=no
        owner=0 group=0 mode=0644
      notify:
        - restart dovecot

    - name: Copy /etc/dovecot/conf.d/10-logging.conf
      template: src=configs/etc/dovecot/conf.d/10-logging.conf.j2
        dest=/etc/dovecot/conf.d/10-logging.conf
        backup=no
        owner=0 group=0 mode=0644
      notify:
        - restart dovecot

    - name: Copy /etc/dovecot/conf.d/10-mail.conf
      template: src=configs/etc/dovecot/conf.d/10-mail.conf.j2
        dest=/etc/dovecot/conf.d/10-mail.conf
        backup=no
        owner=0 group=0 mode=0644
      notify:
        - restart dovecot

    - name: Copy /etc/dovecot/conf.d/10-master.conf
      template: src=configs/etc/dovecot/conf.d/10-master.conf.j2
        dest=/etc/dovecot/conf.d/10-master.conf
        backup=no
        owner=0 group=0 mode=0644
      notify:
        - restart dovecot

    - name: Copy /etc/dovecot/conf.d/10-ssl.conf
      template: src=configs/etc/dovecot/conf.d/10-ssl.conf.j2
        dest=/etc/dovecot/conf.d/10-ssl.conf
        backup=no
        owner=0 group=0 mode=0644
      notify:
        - restart dovecot

    - name: Copy /etc/dovecot/conf.d/10-tcpwrapper.conf
      template: src=configs/etc/dovecot/conf.d/10-tcpwrapper.conf.j2
        dest=/etc/dovecot/conf.d/10-tcpwrapper.conf
        backup=no
        owner=0 group=0 mode=0644
      notify:
        - restart dovecot

    - name: Copy /etc/dovecot/conf.d/15-lda.conf
      template: src=configs/etc/dovecot/conf.d/15-lda.conf.j2
        dest=/etc/dovecot/conf.d/15-lda.conf
        backup=no
        owner=0 group=0 mode=0644
      notify:
        - restart dovecot

    - name: Copy /etc/dovecot/conf.d/15-mailboxes.conf
      template: src=configs/etc/dovecot/conf.d/15-mailboxes.conf.j2
        dest=/etc/dovecot/conf.d/15-mailboxes.conf
        backup=no
        owner=0 group=0 mode=0644
      notify:
        - restart dovecot

    - name: Copy /etc/dovecot/conf.d/20-imap.conf
      template: src=configs/etc/dovecot/conf.d/20-imap.conf.j2
        dest=/etc/dovecot/conf.d/20-imap.conf
        backup=no
        owner=0 group=0 mode=0644
      notify:
        - restart dovecot

    - name: Copy /etc/dovecot/conf.d/20-lmtp.conf
      template: src=configs/etc/dovecot/conf.d/20-lmtp.conf.j2
        dest=/etc/dovecot/conf.d/20-lmtp.conf
        backup=no
        owner=0 group=0 mode=0644
      notify:
        - restart dovecot

    - name: Copy /etc/dovecot/conf.d/20-managesieve.conf
      template: src=configs/etc/dovecot/conf.d/20-managesieve.conf.j2
        dest=/etc/dovecot/conf.d/20-managesieve.conf
        backup=no
        owner=0 group=0 mode=0644
      notify:
        - restart dovecot

    - name: Copy /etc/dovecot/conf.d/20-pop3.conf
      template: src=configs/etc/dovecot/conf.d/20-pop3.conf.j2
        dest=/etc/dovecot/conf.d/20-pop3.conf
        backup=no
        owner=0 group=0 mode=0644
      notify:
        - restart dovecot

    - name: Copy /etc/dovecot/conf.d/90-acl.conf
      template: src=configs/etc/dovecot/conf.d/90-acl.conf.j2
        dest=/etc/dovecot/conf.d/90-acl.conf
        backup=no
        owner=0 group=0 mode=0644
      notify:
        - restart dovecot

    - name: Copy /etc/dovecot/conf.d/90-plugin.conf
      template: src=configs/etc/dovecot/conf.d/90-plugin.conf.j2
        dest=/etc/dovecot/conf.d/90-plugin.conf
        backup=no
        owner=0 group=0 mode=0644
      notify:
        - restart dovecot

    - name: Copy /etc/dovecot/conf.d/90-quota.conf
      template: src=configs/etc/dovecot/conf.d/90-quota.conf.j2
        dest=/etc/dovecot/conf.d/90-quota.conf
        backup=no
        owner=0 group=0 mode=0644
      notify:
        - restart dovecot

    - name: Copy /etc/dovecot/conf.d/90-sieve-extprograms.conf
      template: src=configs/etc/dovecot/conf.d/90-sieve-extprograms.conf.j2
        dest=/etc/dovecot/conf.d/90-sieve-extprograms.conf
        backup=no
        owner=0 group=0 mode=0644
      notify:
        - restart dovecot

    - name: Copy /etc/dovecot/conf.d/90-sieve.conf
      template: src=configs/etc/dovecot/conf.d/90-sieve.conf.j2
        dest=/etc/dovecot/conf.d/90-sieve.conf
        backup=no
        owner=0 group=0 mode=0644
      notify:
        - restart dovecot

    - name: Copy /etc/dovecot/conf.d/auth-sql.conf.ext
      template: src=configs/etc/dovecot/conf.d/auth-sql.conf.ext.j2
        dest=/etc/dovecot/conf.d/auth-sql.conf.ext
        backup=no
        owner=0 group=0 mode=0644
      notify:
        - restart dovecot

    - name: Create /etc/dovecot/sieve-before directory
      action: file path=/etc/dovecot/sieve-before state=directory
        owner=0 group=0 mode=0755

    #         #
    # Postfix #
    #         #

    - name: Copy /etc/postfix/main.cf
      template: src=configs/etc/postfix/main.cf.j2
        dest=/etc/postfix/main.cf
        backup=no
        owner=0 group=0 mode=0644
      notify:
        - restart postfix

    - name: Copy /etc/postfix/master.cf
      template: src=configs/etc/postfix/master.cf.j2
        dest=/etc/postfix/master.cf
        backup=no
        owner=0 group=0 mode=0644
      notify:
        - restart postfix

    - name: Create /etc/postfix/conf.d directory
      action: file path=/etc/postfix/conf.d state=directory
        owner=0 group=0 mode=0755

    - name: Copy /etc/postfix/conf.d/helo_access
      action: copy src=configs/etc/postfix/conf.d/helo_access
        dest=/etc/postfix/conf.d/helo_access
        owner=0 group=0 mode=644
      notify:
        - postmap helo_access

    - name: Copy /etc/postfix/conf.d/postscreen_access.cidr
      action: copy src=configs/etc/postfix/conf.d/postscreen_access.cidr
        dest=/etc/postfix/conf.d/postscreen_access.cidr
        owner=0 group=0 mode=644

    - name: Copy /etc/postfix/conf.d/sender_access
      action: copy src=configs/etc/postfix/conf.d/sender_access
        dest=/etc/postfix/conf.d/sender_access
        owner=0 group=0 mode=644
      notify:
        - postmap sender_access

    - name: Copy /etc/postfix/conf.d/tls_policy
      action: copy src=configs/etc/postfix/conf.d/tls_policy
        dest=/etc/postfix/conf.d/tls_policy
        owner=0 group=0 mode=644
      notify:
        - postmap tls_policy

    - name: Copy /etc/postfix/conf.d/relay_passwords
      template: src=configs/etc/postfix/conf.d/relay_passwords.j2
        dest=/etc/postfix/conf.d/relay_passwords
        backup=no
        owner=0 group=0 mode=0600
      notify:
        - postmap relay_passwords

    - name: Copy /etc/postfix/conf.d/mysql-virtual-alias-maps.cf
      template: src=configs/etc/postfix/conf.d/mysql-virtual-alias-maps.cf.j2
        dest=/etc/postfix/conf.d/mysql-virtual-alias-maps.cf
        backup=no
        owner=0 group=0 mode=0644
      notify:
        - restart postfix

    - name: Copy /etc/postfix/conf.d/mysql-virtual-mailbox-domains.cf
      template: src=configs/etc/postfix/conf.d/mysql-virtual-mailbox-domains.cf.j2
        dest=/etc/postfix/conf.d/mysql-virtual-mailbox-domains.cf
        backup=no
        owner=0 group=0 mode=0644
      notify:
        - restart postfix

    - name: Copy /etc/postfix/conf.d/mysql-virtual-mailbox-maps.cf
      template: src=configs/etc/postfix/conf.d/mysql-virtual-mailbox-maps.cf.j2
        dest=/etc/postfix/conf.d/mysql-virtual-mailbox-maps.cf
        backup=no
        owner=0 group=0 mode=0644
      notify:
        - restart postfix

    - name: Copy /etc/postfix/conf.d/mysql-virtual-relay-domains.cf
      template: src=configs/etc/postfix/conf.d/mysql-virtual-relay-domains.cf.j2
        dest=/etc/postfix/conf.d/mysql-virtual-relay-domains.cf
        backup=no
        owner=0 group=0 mode=0644
      notify:
        - restart postfix

    - name: Generating 2048 dhparam
      openssl_dhparam:
        path: /etc/postfix/dh2048.pem
        size: 2048

    - name: Generating 512 dhparam
      openssl_dhparam:
        path: /etc/postfix/dh512.pem
        size: 512

  handlers:
    - name: restart opendkim
      service: name=opendkim state=restarted

    - name: restart dovecot
      service: name=dovecot state=restarted

    - name: restart postfix
      service: name=postfix state=restarted

    - name: postmap helo_access
      command: /usr/sbin/postmap /etc/postfix/conf.d/helo_access

    - name: postmap sender_access
      command: /usr/sbin/postmap /etc/postfix/conf.d/sender_access

    - name: postmap tls_policy
      command: /usr/sbin/postmap /etc/postfix/conf.d/tls_policy

    - name: postmap relay_passwords
      command: /usr/sbin/postmap /etc/postfix/conf.d/relay_passwords
