# Sets up a minecraft server
#
# - Set hostname to FQDN
# - Run base-config playbook
# - Mount /minecraft for config, world
# - chown -R minecraft:minecraft /minecraft
# - Run this playbook
# - SSH into server and change eula.txt file so eula=true (only needs to be done once per /minecraft drive)
# - service minecraft restart
# - Done
#
# Author: Chuck Findlay <chuck@findlayis.me>
# License: LGPL v3.0
- hosts: minecraftservers
  user: root

  vars_files:
    - minecraft.yaml.vars

  tasks:
    - name: Update apt cache
      apt: update_cache=yes cache_valid_time=86400

    - name: Install depends
      apt: name={{ item }} state=latest
      with_items:
        - screen
        - openjdk-8-jre-headless

    #           #
    # Scripting #
    #           #
    - name: Upload /usr/local/bin/minecraft-attach.sh
      action: copy src=configs/usr/local/bin/minecraft-attach.sh
        dest=/usr/local/bin/minecraft-attach.sh
        owner=0 group=0 mode=0755

    - name: Upload /usr/local/bin/minecraft-scaledown.sh
      action: copy src=configs/usr/local/bin/minecraft-scaledown.sh
        dest=/usr/local/bin/minecraft-scaledown.sh
        owner=0 group=0 mode=0755
      notify:
        - reload systemd
        - enable minecraft-scaledown
        - restart minecraft-scaledown

    #                          #
    # Service account creation #
    #                          #
    - name: Create minecraft group
      group:
        name: minecraft
        state: present
        gid: 5000

    - name: Create minecraft account
      user:
        name: minecraft
        group: minecraft
        state: present
        home: /minecraft
        password_lock: yes
        create_home: no
        shell: /bin/bash
        uid: 5000

    #                #
    # ufw (firewall) #
    #                #

    - name: Allow port 25565 (TCP/UDP) in
      ufw:
          rule: allow
          port: 25565

    #         #
    # Systemd #
    #         #

    - name: Copy /etc/systemd/system/minecraft.service
      template: src=configs/etc/systemd/system/minecraft.service.j2
        dest=/etc/systemd/system/minecraft.service
        backup=no
        owner=0 group=0 mode=0644
      notify:
        - reload systemd
        - enable minecraft
        - restart minecraft

    - name: Copy /etc/systemd/system/minecraft-scaledown.service
      template: src=configs/etc/systemd/system/minecraft-scaledown.service.j2
        dest=/etc/systemd/system/minecraft-scaledown.service
        backup=no
        owner=0 group=0 mode=0644
      notify:
        - reload systemd
        - enable minecraft-scaledown
        - restart minecraft-scaledown

    #          #
    # Download #
    #          #

    - name: Check if server .jar file exists exists
      stat:
        path: /srv/minecraft_server.{{ minecraft_version }}.jar
      register: jar_result

    - name: Downloading server .jar file if needed
      command: /usr/bin/wget {{ minecraft_server_url }} -O /srv/minecraft_server.{{ minecraft_version }}.jar
      when: jar_result.stat.exists == False 

  handlers:
    - name: reload systemd
      systemd:
        daemon_reload: yes

    - name: enable minecraft
      systemd:
        name: minecraft
        enabled: yes
        masked: no

    - name: restart minecraft
      service: name=minecraft state=restarted

    - name: enable minecraft-scaledown
      systemd:
        name: minecraft-scaledown
        enabled: yes
        masked: no

    - name: restart minecraft-scaledown
      service: name=minecraft-scaledown state=restarted