# Sets up a webserver (assumes Google Cloud Services will be used)
#
# - Edit www-servers.yaml.vars & tls.vars
# - Put site configs in configs/etc/nginx/sites
# 
# Author: Chuck Findlay <chuck@findlayis.me>
# License: LGPL v3.0
- hosts: wwwservers
  user: root

  vars_files:
    - www-servers.yaml.vars
    - tls.vars

  tasks:
    - name: Update apt cache
      apt: update_cache=yes cache_valid_time=86400

    - name: Install depends
      apt:
        name:
        - nginx
        - php-fpm
        - php-mysql
        - libnginx-mod-http-headers-more-filter
        - certbot
        state: present
        autoclean: yes

    #                #
    # ufw (firewall) #
    #                #

    - name: Allow HTTP on port 80/tcp
      ufw:
          rule: allow
          port: '80'
          proto: tcp

    - name: Allow HTTPS on port 443/tcp
      ufw:
          rule: allow
          port: '443'
          proto: tcp

    #                     #
    # nginx configuration #
    #                     #

    - name: Copy /etc/nginx/nginx.conf
      template: src=configs/etc/nginx/nginx.conf.j2
        dest=/etc/nginx/nginx.conf
        backup=no
        owner=0 group=0 mode=0644
      notify:
        - restart nginx

    - name: Copy /etc/nginx/conf.d/headers-more-filter.conf
      template: src=configs/etc/nginx/conf.d/headers-more-filter.conf.j2
        dest=/etc/nginx/conf.d/headers-more-filter.conf
        backup=no
        owner=0 group=0 mode=0644
      notify:
        - restart nginx

    - name: Copy site configuration files to /etc/nginx/sites
      action: copy src=configs/etc/nginx/sites/
        dest=/etc/nginx/sites/
        owner=root group=root mode=0644
      notify:
        - restart nginx

    #                                #
    # SSL Configuration/Installation #
    #                                #

    - name: Generating 4096 dhparam
      openssl_dhparam:
        path: /etc/nginx/dh4096.pem
        size: 4096

  handlers:
    - name: restart nginx
      service: name=nginx state=restarted