# Author: Chuck Findlay <chuck@findlayis.me>
# License: LGPL v3.0
- hosts: webservers
  user: root

  vars_files:
    - www-servers.yaml.vars
    - tls.vars

  tasks:
    - name: Update apt cache
      apt: update_cache=yes cache_valid_time=86400

    - name: Install required programs
      apt: name={{ item }} state=latest
      with_items:
        - nginx
        - php-fpm
        - php-mysql

    - name: Allow HTTP on port 80/tcp
      ufw:
          rule: allow
          port: 80
          proto: tcp

    - name: Allow HTTPS on port 443/tcp
      ufw:
          rule: allow
          port: 443
          proto: tcp
